server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    absolute_redirect off;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml font/ttf;

    location = / {
        return 301 /fr/;
    }

    location ~ ^/(assets/|.*\.(png|svg|ico|ttf|webmanifest))$ {
        try_files $uri /fr$uri =404;
    }

    location /fr/ {
        try_files $uri $uri/ /fr/index.html;
    }

    location /en-US/ {
        try_files $uri $uri/ /en-US/index.html;
    }

    location / {
        try_files $uri $uri/ /fr/index.html;
    }
}